services:
    postgres:
        image: postgres
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql
        networks:
            - network

networks:
    network:
        driver: bridge

volumes:
    postgres:
        driver: local
